version: "3.8"


services:
  fastapi:
    container_name: backend_app
    build: .
    command: uvicorn anatomic.app:app --reload --host 0.0.0.0 --port 10000
    ports:
      - '10000:10000'
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
    driver: bridge