version: "3.8"

#services:
#  db:
#    container_name: atomic_postgresql
#    image: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: database
#    ports:
#      - "5432:5432"

services:
  fastapi:
    container_name: backend_app
    build: .
    command: uvicorn anatomic.app:app --reload --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
    driver: bridge