"""empty message

Revision ID: 821445751957
Revises: bb60d3356e95
Create Date: 2024-05-01 17:27:25.314015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821445751957'
down_revision: Union[str, None] = 'bb60d3356e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('topic', sa.Column('content_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'topic', 'topic_content', ['content_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_column('topic', 'content_id')
    op.drop_table('topic_content')
    # ### end Alembic commands ###
