"""empty message

Revision ID: fa671506378d
Revises: a4d2c0b9cbaa
Create Date: 2024-04-28 12:13:56.090777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa671506378d'
down_revision: Union[str, None] = 'a4d2c0b9cbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'progress',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'progress',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
